In [3]:
import numpy as np

In [7]:
person_data_def = [('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [10]:
people_array = np.zeros((4), dtype=person_data_def)

In [11]:
people_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [13]:
people_array[0] = ('Sema', 59, 167,27)

In [14]:
people_array[3] = ('Josef', 67, 175, 27)

In [15]:
people_array

array([(b'Sema', 59., 167., 27), (b'',  0.,   0.,  0),
       (b'',  0.,   0.,  0), (b'Josef', 67., 175., 27)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [17]:
ages = people_array['age']

In [22]:
ages, ages.dtype

(array([27,  0,  0, 27]), dtype('int64'))

In [24]:
people_array['name']

array([b'Sema', b'', b'', b'Josef'], dtype='|S6')

In [31]:
print(people_array[['name','age']])

[(b'Sema', 27) (b'',  0) (b'',  0) (b'Josef', 27)]


In [33]:
print(people_array.shape, people_array.dtype)

(4,) [('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')]


In [37]:
##access and change the column names

people_array.dtype.names

('name', 'height', 'weight', 'age')

In [38]:
people_array.dtype.names = ('Name', 'Height', 'Weight', 'Age')

In [39]:
people_array.dtype.names

('Name', 'Height', 'Weight', 'Age')

### Load data into structured arrays

In [40]:
dtype = [('year','i8'), ('hare', 'f8'), ('lynx', 'f8'), ('carrot', 'f8')]

In [42]:
population = np.loadtxt('populations.txt', dtype= dtype)

In [43]:
population

array([(1900, 30000.,  4000., 48300.), (1901, 47200.,  6100., 48200.),
       (1902, 70200.,  9800., 41500.), (1903, 77400., 35200., 38200.),
       (1904, 36300., 59400., 40600.), (1905, 20600., 41700., 39800.),
       (1906, 18100., 19000., 38600.), (1907, 21400., 13000., 42300.),
       (1908, 22000.,  8300., 44500.), (1909, 25400.,  9100., 42100.),
       (1910, 27100.,  7400., 46000.), (1911, 40300.,  8000., 46800.),
       (1912, 57000., 12300., 43800.), (1913, 76600., 19500., 40900.),
       (1914, 52300., 45700., 39400.), (1915, 19500., 51100., 39000.),
       (1916, 11200., 29700., 36700.), (1917,  7600., 15800., 41800.),
       (1918, 14600.,  9700., 43300.), (1919, 16200., 10100., 41300.),
       (1920, 24700.,  8600., 47300.)],
      dtype=[('year', '<i8'), ('hare', '<f8'), ('lynx', '<f8'), ('carrot', '<f8')])

In [44]:
# alternative way to load data from txt

population2 = np.genfromtxt('populations.txt',
                            names = True,
                            dtype=['int', 'float', 'float', 'float']
                           )

In [45]:
population2

array([(1900, 30000.,  4000., 48300.), (1901, 47200.,  6100., 48200.),
       (1902, 70200.,  9800., 41500.), (1903, 77400., 35200., 38200.),
       (1904, 36300., 59400., 40600.), (1905, 20600., 41700., 39800.),
       (1906, 18100., 19000., 38600.), (1907, 21400., 13000., 42300.),
       (1908, 22000.,  8300., 44500.), (1909, 25400.,  9100., 42100.),
       (1910, 27100.,  7400., 46000.), (1911, 40300.,  8000., 46800.),
       (1912, 57000., 12300., 43800.), (1913, 76600., 19500., 40900.),
       (1914, 52300., 45700., 39400.), (1915, 19500., 51100., 39000.),
       (1916, 11200., 29700., 36700.), (1917,  7600., 15800., 41800.),
       (1918, 14600.,  9700., 43300.), (1919, 16200., 10100., 41300.),
       (1920, 24700.,  8600., 47300.)],
      dtype=[('year', '<i8'), ('hare', '<f8'), ('lynx', '<f8'), ('carrot', '<f8')])

In [46]:
population.dtype, population2.dtype

(dtype([('year', '<i8'), ('hare', '<f8'), ('lynx', '<f8'), ('carrot', '<f8')]),
 dtype([('year', '<i8'), ('hare', '<f8'), ('lynx', '<f8'), ('carrot', '<f8')]))

In [56]:
people_array[0:1]

array([(b'Sema', 59., 167., 27)],
      dtype=[('Name', 'S6'), ('Height', '<f8'), ('Weight', '<f8'), ('Age', '<i8')])

In [58]:
people_recarray = np.rec.array(people_array)

In [60]:
people_recarray[0:1].Age

array([27])

In [67]:
a = np.random.uniform(-1,1, (5,5))
print(a)

[[-0.70503649  0.1617549   0.26237158 -0.57102257  0.01717127]
 [ 0.36817236 -0.65540163  0.35704151 -0.52964603  0.97837346]
 [ 0.15399821 -0.12542465 -0.26799988  0.00977157 -0.1660708 ]
 [-0.54964568  0.77794078 -0.66872623  0.83018729 -0.02840734]
 [-0.83011049  0.99097164  0.02646207  0.33534501  0.9219928 ]]


In [70]:
#return the index of max value of the matrix

np.argmax(a), np.max(a)

(21, 0.9909716375884994)

In [4]:
## indexing with boolean filter
ab= np.random.uniform(-1,1,(5,5))
print(ab)

[[ 0.2113812  -0.49168776 -0.64186033  0.77185068 -0.10282265]
 [-0.63454647 -0.54804184  0.8295588  -0.42479529 -0.52715346]
 [-0.31537523  0.95242232 -0.02525931  0.50996867 -0.27957747]
 [ 0.10313789  0.61230319  0.50225943 -0.9718727   0.19538909]
 [-0.67566792 -0.34638844 -0.08135379  0.63576073  0.4035722 ]]


In [6]:
index = ab >0
print(index)

[[ True False False  True False]
 [False False  True False False]
 [False  True False  True False]
 [ True  True  True False  True]
 [False False False  True  True]]


In [11]:
print(ab[:,0][index[:,0]])

[0.2113812  0.10313789]
